name: invogen
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  path_provider: ^2.0.15
  hive_flutter: ^1.1.0
  contained_tab_bar_view: ^0.8.0
  list_country_picker: ^0.0.1
  image_picker: ^1.0.1
  dropdown_search: ^5.0.6
  searchable_paginated_dropdown: ^1.2.0
  flutter_holo_date_picker: ^1.1.0
  syncfusion_flutter_pdfviewer: ^22.2.12
  flutter_file_downloader: ^1.1.2
  flutter_email_sender: 
  device_info_plus:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0





flutter:

  uses-material-design: true
 
  assets:
    - assets/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  
  
